<?php

namespace Database\Seeders;

use App\Models\SalesRiskPolicy;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SalesRiskPoliciySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $sales_risk_policies = array(
            [
                "id" => 1,
                "title" => "1-4 hourly rate:",
                "parent_id" => NULL,
                "type" => "parent",
                "value_type" => NULL,
                "value" => NULL,
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:54:11",
                "updated_at" => "2024-03-05 06:54:11",
            ],
            [
                "id" => 2,
                "title" => "Greater than $10",
                "parent_id" => 1,
                "type" => "greater_than",
                "value_type" => "currency",
                "value" => "10",
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 3,
                "title" => "$11-15 usd",
                "parent_id" => 1,
                "type" => "range",
                "value_type" => "currency",
                "value" => "11, 15",
                "point" => -0.80,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 4,
                "title" => "$21-30 usd",
                "parent_id" => 1,
                "type" => "range",
                "value_type" => "currency",
                "value" => "21, 30",
                "point" => -0.50,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 5,
                "title" => "$30+ usd",
                "parent_id" => 1,
                "type" => "greater_than",
                "value_type" => "currency",
                "value" => "30",
                "point" => 1.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 6,
                "title" => "Milestone percentages:",
                "parent_id" => NULL,
                "type" => "fixed",
                "value_type" => "percentage",
                "value" => "0",
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 7,
                "title" => "Greater Than 50%",
                "parent_id" => 6,
                "type" => "greater_than",
                "value_type" => "percentage",
                "value" => "50",
                "point" => -2.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 8,
                "title" => "0",
                "parent_id" => 6,
                "type" => "fixed",
                "value_type" => "percentage",
                "value" => "0",
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 9,
                "title" => "Less than 50%",
                "parent_id" => 6,
                "type" => "less_than",
                "value_type" => "percentage",
                "value" => "50",
                "point" => 0.50,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 10,
                "title" => "Client-issued theats:",
                "parent_id" => NULL,
                "type" => "parent",
                "value_type" => NULL,
                "value" => NULL,
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 11,
                "title" => "Yes",
                "parent_id" => 10,
                "type" => "yes_no",
                "value_type" => NULL,
                "value" => "1",
                "point" => -1.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 12,
                "title" => "No",
                "parent_id" => 10,
                "type" => "yes_no",
                "value_type" => NULL,
                "value" => "0",
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-05 06:56:13",
                "updated_at" => "2024-03-05 06:56:13",
            ],
            [
                "id" => 13,
                "title" => "Client's Country:",
                "parent_id" => NULL,
                "type" => "parent",
                "value_type" => NULL,
                "value" => NULL,
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-06 10:30:25",
                "updated_at" => "2024-03-06 10:30:30",
            ],
            [
                "id" => 14,
                "title" => "Tier1 ",
                "parent_id" => 13,
                "type" => "list",
                "value_type" => NULL,
                "value" => "{\"AF\":\"Afghanistan\",\"AL\":\"Albania\",\"DZ\":\"Algeria\"}",
                "point" => 0.00,
                "department" => "wd",
                "status" => "1",
                "comment" => NULL,
                "created_at" => "2024-03-06 10:36:50",
                "updated_at" => "2024-03-06 10:36:53",
            ],

        );

        foreach ($sales_risk_policies as $item) {
            SalesRiskPolicy::create($item);
        }
    }
}
