export const bid_insights_Data = [
    {
        id: 1,
        project:
            "Website redesign for company X fojdgk efihel rwiohwti wriohtnw",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: 3.5,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: true,
    },
    {
        id: 2,
        project: "Landscaping Website",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: 3.5,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: false,
    },
    {
        id: 3,
        project: "Minimalist Web Design",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: null,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: false,
    },
    {
        id: 4,
        project: "Landscaping Website",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: null,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: true,
    },
    {
        id: 5,
        project: "Minimalist Web Design",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: 3.5,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: true,
    },
    {
        id: 6,
        project: "Landscaping Website",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: 3.5,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: true,
    },
    {
        id: 7,
        project: "Minimalist Web Design",
        time_to_bid: "1 minute, 12 seconds",
        bid_rank: "#2 of 104 bids",
        winning_bid: null,
        your_bid: 900.0,
        currency: {
            code: "CAD",
            symbol: "$",
        },
        actions_taken: ["view", "bookmark", "check"],
        client_info: {
            user_id: 34567,
            profile_image_url: "https://i.ibb.co/jHYks1p/client-image.png",
            name: "John Doe",
            location: {
                iso: "US",
                country: "United States",
                city: "California",
            },
            average_rating: 3.5,
            reviews_count: 2,
            member_since: "2024-06-25 07:37:00",
            client_engagement: {
                contracted_freelancer: 0,
                invite_freelancer: 0,
                completed_project: 0,
            },
            client_verification: {
                identity_verified: true,
                payment_verified: true,
                deposit_made: true,
                email_verified: true,
                profile_completed: true,
                phone_verified: true,
            },
        },
        chat_initiated: true,
    },
];
