[
    {
        id: 2337,
        name: "Chinmoy Biswas",
        user_name: null,
        email: "chinmoy1@seopage1.net",
        two_factor_secret: null,
        two_factor_recovery_codes: null,
        two_factor_confirmed: 0,
        two_factor_email_confirmed: 0,
        image: "avatar_blank.png",
        mobile: "01987966848",
        gender: "male",
        salutation: "mr",
        locale: "en",
        status: "active",
        login: "enable",
        onesignal_player_id: null,
        last_login: "2024-02-20T12:33:43+06:00",
        email_notifications: 1,
        country_id: 18,
        dark_theme: 0,
        rtl: 0,
        two_fa_verify_via: null,
        two_factor_code: "960970",
        two_factor_expires_at: "2023-11-24T15:43:44+06:00",
        admin_approval: 1,
        permission_sync: 1,
        google_calendar_status: 1,
        role_id: 5,
        shift: null,
        activation_status: 1,
        image_url: "http://127.0.0.1:8000/user-uploads/avatar/avatar_blank.png",
        modules: [
            "clients",
            "projects",
            "tickets",
            "invoices",
            "estimates",
            "events",
            "messages",
            "tasks",
            "timelogs",
            "contracts",
            "notices",
            "payments",
            "orders",
            "knowledgebase",
            "employees",
            "attendance",
            "expenses",
            "leaves",
            "leads",
            "holidays",
            "products",
            "reports",
            "settings",
        ],
        user_other_role: true,
        role: [
            {
                user_id: 2337,
                role_id: 2,
            },
            {
                user_id: 2337,
                role_id: 5,
            },
        ],
        client_details: null,
        session: null,
        employee_detail: {
            id: 64,
            user_id: 2337,
            employee_id: "SEOPAGE1/ID/23/0136",
            address: "Bosoti Housing, Mirpur-2, Dhaka, Bangladesh",
            hourly_rate: null,
            slack_username: "chinmoy",
            department_id: 1,
            designation_id: 24,
            joining_date: "2023-11-08T06:00:00+06:00",
            last_date: null,
            added_by: 218,
            last_updated_by: 2337,
            attendance_reminder: null,
            date_of_birth: "1996-06-16T00:00:00+06:00",
            calendar_view: "task,events,holiday,tickets,leaves",
            about_me: "Senior Wordpress Developer",
            reporting_to: 208,
            upcoming_birthday: "2024-06-16",
            designation: {
                id: 24,
                name: "Senior Web Developer",
                parent_id: 23,
                added_by: null,
                last_updated_by: null,
            },
        },
    },
];
