
import { User } from "../../utils/user-details";
import { LeadDeveloperTableColumns } from "../components/table/columns/LeadDeveloperTableColumns";

const auth = new User(window.Laravel.user);

/**
 * @typedef {Object} LeadDevDashboardData
 * @property {number} id - Unique identifier for the dashboard data item.
 * @property {string} title - Title of the dashboard item.
 * @property {string|null} subTitle - Subtitle of the dashboard item.
 * @property {string|null} value - The value associated with the dashboard item.
 * @property {string|null} valueTypeBefore - Any value type string to be shown before the value.
 * @property {string|null} valueTypeAfter - Any value type string to be shown after the value.
 * @property {string} key - The key associated with the dashboard item.
 * @property {string|null} info - Additional information about the dashboard item.
 * @property {boolean} hasPermissionForModal - Flag indicating if the user has permission to view the modal for this item.
 * @property {string} query - The query key used to fetch the data.
 * @property {string} responseKey - The key used to extract the relevant data from the response.
 * @property {function(Object[]): Object[]} formateResponse - Function to format the response data.
 * @property {Object[]} tableColumn - The columns to be shown in the table.
 * @property {Object[]} isShowModalExtraInfo - Extra information to be shown in the modal.
 * @property {boolean} isModalOpen - Flag indicating if the modal is open.
 */

/**
 * Lead Dev Dashboard Data Constants
 * @type {LeadDevDashboardData[]}
 */

export const LeadDeveloperDataTitle = [
  {
    id: 1,
    title: "Number Of Tasks Received",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_tasks_received_lead",
    info: null,
    hasPermissionForModal: auth.getRoleId() === 1,
    query: "leads_received",
    responseKey: "number_of_tasks_received_lead_data",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Received Tasks",
        key: "number_of_tasks_received_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 2,
    title: "Number Of Submitted Tasks",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "submit_number_of_tasks_in_this_month_lead",
    info: null,
    hasPermissionForModal: auth.getRoleId() === 1,
    query: "leads_received",
    responseKey: "submit_number_of_tasks_in_this_month_lead_data",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 3,
    title: "Number Of Approved Tasks On 1st Attempt By Project Manager",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "first_attempt_approve_task_in_this_month_lead",
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  },
  {
    id: 4,
    title: "Number Of Approved Tasks On 1st Attempt By Client",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "first_attempt_approve_task_in_this_month_client_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "first_attempt_approve_task_data_client_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Approved Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 5,
    title: "Avg Number Of Attempts Needed For Approval By Project Manager",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "average_submission_aproval_in_this_month_lead",
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  },
  {
    id: 6,
    title: "Avg Number Of Attempts Needed For Approval By Client",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "average_submission_aproval_in_this_month_client_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "first_attempt_approve_task_data_client_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 7,
    title: "Percentage Of Tasks With Revisions",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: "%",
    key: "percentage_of_tasks_with_revision_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "revision_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [{
      id: "1",
      title: "Submitted Tasks",
      key: "revision_data_lead",
      value: null,
      valueTypeBefore: null,
      valueTypeAfter: null,
    }],
    isModalOpen: false,
  },
  {
    id: 8,
    title: "Total Number Of Revisions",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_total_revision_for_this_month_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "revision_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [{
      id: "1",
      title: "Submitted Tasks",
      key: "submit_number_of_tasks_in_this_month_lead",
      value: null,
      valueTypeBefore: null,
      valueTypeAfter: null,
    }],
    isModalOpen: false,
  },
  {
    id: 9,
    title: "Average Task Submission Time (In Days)",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: "Days",
    key: "average_submission_day_in_this_month_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "average_submit_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 10,
    title: "Average Number Of In-Progress Tasks",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "average_in_progress_date_range_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "total_in_progress_date_range_table_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 11,
    title: "Percentage Of Tasks Where Deadline Was Missed",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: "%",
    key: "percentage_of_tasks_deadline_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "estimate_missed_task_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 12,
    title: "Percentage Of Tasks Where Given Estimated Time Was Missed",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "percentage_number_task_cross_estimate_time_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "estimate_missed_task_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 13,
    title: "Rejection Rate", // 
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "rejection_rate_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  },
  {
    id: 14,
    title: "Cancelation Rate",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "cancelation_rate_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  }, {
    id: 15,
    title: "Rate Of Reassign",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "rate_of_reassign_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  },
  {
    id: 16,
    title: "No. of disputes filed",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_dispute_filed_own_lead",
    info: null,
    hasPermissionForModal: false,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [],
    isModalOpen: false,
  },
  {
    id: 17,
    title: "No. of disputes",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_dispute_filed_all_lead",
    info: {
      content: "Overall"
    },
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "number_of_dispute_filed_all_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal, 
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 18,
    title: "No. of disputes lost",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_dispute_lost_own_lead",
    info: {
      content: "Raised By Developer"
    },
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "number_of_dispute_lost_own_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 19,
    title: "No. of disputes lost",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: null,
    key: "number_of_dispute_lost_all_lead",
    info: {
      content: "Overall"
    },
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "number_of_dispute_lost_all_data_lead",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  },
  {
    id: 20,
    title: "Hours spent in revisions",
    subTitle: null,
    value: 10,
    valueTypeBefore: null,
    valueTypeAfter: "Hours",
    key: "spent_revision_developer_lead",
    info: null,
    hasPermissionForModal: true,
    query: "leads_received",
    responseKey: "number_of_leads_received_list",
    formateResponse: () => {},
    tableColumn: LeadDeveloperTableColumns?.Modal,
    isShowModalExtraInfo: [
      {
        id: "1",
        title: "Submitted Tasks",
        key: "submit_number_of_tasks_in_this_month_lead",
        value: null,
        valueTypeBefore: null,
        valueTypeAfter: null,
      },
    ],
    isModalOpen: false,
  }
]