
import { User } from "../../utils/user-details";
import { LeadDeveloperTableColumns } from "../components/table/columns/LeadDeveloperTableColumns";

const auth = new User(window.Laravel.user);

/**
 * Lead Developer All Dashboard Data
 * @type {Array} - Array of Objects
 * @property {number} id - Unique Identifier
 * @property {string} title - Title of the data
 * @property {string} subTitle - Subtitle of the data
 * @property {number} value - Value of the data
 * @property {string} key - Unique key of the data
 * @property {string} info - Information of the data 
 * @property {boolean} hasPermissionForModal - has permission to open modal or has not have any modal for this data
 * @property {string} dataFetchUrlApi - API URL for fetching data
 * @property {object} tableColumn - Table Column for this data
 * @property {boolean} isShowModalExtraInfo - Show extra information in modal
 * @property {boolean} isModalOpen - Modal is open or not
 */

export const LeadDeveloperDataTitle = [
  {
    id: 1,
    title: "Number Of Tasks Received",
    subTitle: null,
    value: 10,
    key: "number_of_tasks_received_lead",
    info: null,
    hasPermissionForModal: auth.getRoleId() === 1,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 2,
    title: "Number Of Submitted Tasks",
    subTitle: null,
    value: 10,
    key: "number_of_submitted_tasks_lead",
    info: null,
    hasPermissionForModal: auth.getRoleId() === 1,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 3,
    title: "Number Of Approved Tasks On 1st Attempt By Project Manager",
    subTitle: null,
    value: 10,
    key: "first_attempt_approve_task_in_this_month_lead",
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 4,
    title: "Number Of Approved Tasks On 1st Attempt By Client",
    subTitle: null,
    value: 10,
    key: "first_attempt_approve_task_data_client_lead",
    info: null,
    hasPermissionForModal: auth.getRoleId() === 1,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 5,
    title: "Avg Number Of Attempts Needed For Approval By Project Manager",
    subTitle: null,
    value: 10,
    key: "average_submission_aproval_in_this_month_lead",
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 6,
    title: "Avg Number Of Attempts Needed For Approval By Client",
    subTitle: null,
    value: 10,
    key: "average_submission_aproval_in_this_month_client_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 7,
    title: "Percentage Of Tasks With Revisions",
    subTitle: null,
    value: 10,
    key: "percentage_of_tasks_with_revision_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 8,
    title: "Total Number Of Revisions",
    subTitle: null,
    value: 10,
    key: "first_attempt_approve_task_in_this_month_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 9,
    title: "Average Task Submission Time (In Days)",
    subTitle: null,
    value: 10,
    key: "average_submission_day_in_this_month_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 10,
    title: "Average Number Of In-Progress Tasks",
    subTitle: null,
    value: 10,
    key: "average_in_progress_date_range_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
  },
  {
    id: 11,
    title: "Percentage Of Tasks Where Deadline Was Missed",
    subTitle: null,
    value: 10,
    key: "percentage_of_tasks_deadline_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 12,
    title: "Percentage Of Tasks Where Given Estimated Time Was Missed",
    subTitle: null,
    value: 10,
    key: "percentage_number_task_cross_estimate_time_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 13,
    title: "Rejection Rate", // 
    subTitle: null,
    value: 10,
    key: "rejection_rate_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 14,
    title: "Cancelation Rate",
    subTitle: null,
    value: 10,
    key: "cancelation_rate_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  }, {
    id: 15,
    title: "Rate Of Reassign",
    subTitle: null,
    value: 10,
    key: "rate_of_reassign_lead", // showing Dummy Data in main dashboard
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 16,
    title: "No. of disputes filed",
    subTitle: null,
    value: 10,
    key: "number_of_dispute_filed_own_lead",
    info: null,
    hasPermissionForModal: false,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 17,
    title: " No. of disputes (Overall)",
    subTitle: null,
    value: 10,
    key: "number_of_dispute_filed_all_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 18,
    title: "No. of disputes lost",
    subTitle: "Raised By Developer",
    value: 10,
    key: "number_of_dispute_lost_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 19,
    title: "No. of disputes lost",
    subTitle: "Overall",
    value: 10,
    key: "number_of_dispute_lost_all_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  },
  {
    id: 20,
    title: "Hours spent in revisions",
    subTitle: null,
    value: 10,
    key: "spent_revision_developer_lead",
    info: null,
    hasPermissionForModal: true,
    dataFetchUrlApi: "leadDeveloperData",
    tableColumn: LeadDeveloperTableColumns?.Complete,
    isShowModalExtraInfo: false,
    isModalOpen: false,
  }
]