<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('factors', function (Blueprint $table) {
            $table->id();
            $table->foreignId('criteria_id');
            $table->string('title');
            $table->unsignedTinyInteger('project_type')->comment('1 = Fixed, 2 = Hourly');
            $table->decimal('lower_limit')->nullable();
            $table->decimal('upper_limit')->nullable();
            $table->decimal('lower_limit_top_range')->nullable();
            $table->decimal('upper_limit_bottom_range')->nullable();
            $table->unsignedTinyInteger('limit_type')->nullable()->comment('1 = Range, 2 = Boolean');
            $table->unsignedTinyInteger('limit_unit')->nullable()->comment('1 = Hours, 2 = Percent(%), 3 = Amount($), 4 = Projects, 5 = Others');
            $table->string('lower_limit_condition')->nullable()->comment('>,<,=,=>,=<,!=');
            $table->string('upper_limit_condition')->nullable()->comment('>,<,==,=>,=<,!=');
            $table->string('lower_limit_top_range_condition')->nullable()->comment('>,<,=,=>,=<,!=');
            $table->string('upper_limit_bottom_range_condition')->nullable()->comment('>,<,==,=>,=<,!=');
            $table->string('limit_depend_on_models_and_fields')->nullable()->comment('The limit depend on this model and fields');
            $table->unsignedTinyInteger('point_type')->nullable()->comment('1 = Static, 2 = Percentage');
            $table->decimal('points');
            $table->string('point_depend_on_model')->nullable()->comment('The point depend on this model');
            $table->string('point_depend_on_field')->nullable()->comment('The point depend on this field of defined model');
            $table->unsignedTinyInteger('status')->default(1)->comment('1 = Active, 0 = Deactive');
            $table->timestamps();
        });

        \Illuminate\Support\Facades\DB::table('factors')->insert([
            [
                'id' => 1,
                'criteria_id' => 1,
                'title' => 'Deliverables are signed by the client within (0-48) hours after the entry of the project in the system',
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 48,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Deal', 'field' => 'released_at'], ['model' => 'App\Models\ContractSign', 'field' => 'created_at']]),
                'point_type' => 1,
                'points' => 5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 2,
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by 80%-120%',
                'project_type' => 1,
                'lower_limit' => 80,
                'upper_limit' => 120,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => 5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 3, 
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by 70%-80% or 120%-130%',
                'project_type' => 1,
                'lower_limit' => 70,
                'upper_limit' => 130,
                'lower_limit_top_range' => 80,
                'upper_limit_bottom_range' => 120,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => '>=',
                'upper_limit_bottom_range_condition' => '<',
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => 4,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 4,
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by 60%-70% or 130%-140%',
                'project_type' => 1,
                'lower_limit' => 60,
                'upper_limit' => 140,
                'lower_limit_top_range' => 70,
                'upper_limit_bottom_range' => 130,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => '>=',
                'upper_limit_bottom_range_condition' => '<',
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => 3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 5,
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by 55%-60% or 140%-145%',
                'project_type' => 1,
                'lower_limit' => 55,
                'upper_limit' => 145,
                'lower_limit_top_range' => 60,
                'upper_limit_bottom_range' => 140,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => '>=',
                'upper_limit_bottom_range_condition' => '<',
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => 2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 6,
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by 50%-55% or 145%-150%',
                'project_type' => 1,
                'lower_limit' => 50,
                'upper_limit' => 150,
                'lower_limit_top_range' => 55,
                'upper_limit_bottom_range' => 145,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => '>=',
                'upper_limit_bottom_range_condition' => '<',
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => 1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 7,
                'criteria_id' => 2,
                'title' => 'Estimated hours matching the logged hours by <50% or >150%',
                'project_type' => 1,
                'lower_limit' => 50,
                'upper_limit' => 150,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '>',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => json_encode([['model' => 'App\Models\Task', 'field' => 'estimate_hours'], ['model' => 'App\Models\ProjectTimeLog', 'field' => 'total_hours']]),
                'point_type' => 1,
                'points' => -5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 8,
                'criteria_id' => 3,
                'title' => 'Less than 5% time of estimated time or 1 hour whichever is higher in revision)',
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 5,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 5,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 9,
                'criteria_id' => 3,
                'title' => '5-10% time of the estimated time in revisions',
                'project_type' => 1,
                'lower_limit' => 5,
                'upper_limit' => 10,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 4,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 10,
                'criteria_id' => 3,
                'title' => '10-20% time of the estimated time in revision',
                'project_type' => 1,
                'lower_limit' => 10,
                'upper_limit' => 20,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 3,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 11,
                'criteria_id' => 3,
                'title' => '20-30% time of the estimated time in revision',
                'project_type' => 1,
                'lower_limit' => 20,
                'upper_limit' => 30,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 2.5,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 12,
                'criteria_id' => 3,
                'title' => '30-40% time of the estimated time in revision',
                'project_type' => 1,
                'lower_limit' => 30,
                'upper_limit' => 40,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 2,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 13,
                'criteria_id' => 3,
                'title' => '40-80% time of the estimated time in revision',
                'project_type' => 1,
                'lower_limit' => 40,
                'upper_limit' => 80,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 0,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 14,
                'criteria_id' => 3,
                'title' => '>80% time of the estimated time in revision',
                'project_type' => 1,
                'lower_limit' => 80,
                'upper_limit' => 80,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 2,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => -5,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 15,
                'criteria_id' => 4,
                'title' => 'For marking every milestone as paid',
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '==',
                'upper_limit_condition' => '==',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 16,
                'criteria_id' => 5,
                'title' => 'For completing a project full (With project completion form)',
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '==',
                'upper_limit_condition' => '==',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 1,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 17,
                'criteria_id' => 6,
                'title' => 'If first tasks are created within (0-48) hours',
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 48,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 1,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 18,
                'criteria_id' => 7,
                'title' => 'If the project deadline is met',
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '==',
                'upper_limit_condition' => '==',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 2,
                'points' => 1,
                'point_depend_on_model' => 'App\Models\Project',
                'point_depend_on_field' => 'project_budget'
            ],
            [
                'id' => 19,
                'criteria_id' => 8,
                'title' => "If a PM doesn't submit a task to the client / give revision within 36 hours after it was submitted by the lead developer",
                'project_type' => 1,
                'lower_limit' => 36,
                'upper_limit' => 36,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 20,
                'criteria_id' => 9,
                'title' => "If a project manager can complete 5 project in 7 days",
                'project_type' => 1,
                'lower_limit' => 5,
                'upper_limit' => 8,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '>',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 15,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 21,
                'criteria_id' => 9,
                'title' => "If a project manager can complete 8 project in 7 days",
                'project_type' => 1,
                'lower_limit' => 8,
                'upper_limit' => 10,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '>',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 30,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 22,
                'criteria_id' => 9,
                'title' => "If a project manager can complete 10 project in 7 days",
                'project_type' => 1,
                'lower_limit' => 10,
                'upper_limit' => 10,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '<=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 50,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 23,
                'criteria_id' => 10,
                'title' => "If a project manager can complete 5 project in 12 days",
                'project_type' => 1,
                'lower_limit' => 5,
                'upper_limit' => 8,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '>',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 24,
                'criteria_id' => 10,
                'title' => "If a project manager can complete 8 project in 12 days",
                'project_type' => 1,
                'lower_limit' => 8,
                'upper_limit' => 10,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '>',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 10,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 25,
                'criteria_id' => 10,
                'title' => "If a project manager can complete 10 project in 12 days",
                'project_type' => 1,
                'lower_limit' => 10,
                'upper_limit' => 10,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 4,
                'lower_limit_condition' => '<=',
                'upper_limit_condition' => '<=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 20,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 26,
                'criteria_id' => 11,
                'title' => "$1-400",
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 400,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 3,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 27,
                'criteria_id' => 11,
                'title' => "$401-700",
                'project_type' => 1,
                'lower_limit' => 400,
                'upper_limit' => 700,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 3,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 4,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 28,
                'criteria_id' => 11,
                'title' => "$701-1200",
                'project_type' => 1,
                'lower_limit' => 700,
                'upper_limit' => 1200,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 3,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 29,
                'criteria_id' => 11,
                'title' => "$1201+",
                'project_type' => 1,
                'lower_limit' => 1200,
                'upper_limit' => 1200,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 3,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 7,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 30,
                'criteria_id' => 12,
                'title' => "Task hold time is more than 1 day during the assign phase, hold time will count after 48 hours",
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 31,
                'criteria_id' => 13,
                'title' => "Task hold time is more than 12 hours during the submission phase of new tasks, hold time will count after 12 hours",
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 32,
                'criteria_id' => 14,
                'title' => "Task hold time is more than 4 hours during the submission phase of revisions, hold time will count after 4 hours",
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 33,
                'criteria_id' => 15,
                'title' => "For missing every goal in a regular project",
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 34,
                'criteria_id' => 15,
                'title' => "For missing every goal in a priority project",
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 2,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 35,
                'criteria_id' => 15,
                'title' => "For missing every goal in a high-priority project",
                'project_type' => 1,
                'lower_limit' => 2,
                'upper_limit' => 3,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 36,
                'criteria_id' => 15,
                'title' => "For missing every goal in a top most priority project",
                'project_type' => 1,
                'lower_limit' => 3,
                'upper_limit' => 4,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -4,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 37,
                'criteria_id' => 15,
                'title' => "For missing every goal in a critically sensitive project",
                'project_type' => 1,
                'lower_limit' => 4,
                'upper_limit' => 5,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 38,
                'criteria_id' => 16,
                'title' => "Regular",
                'project_type' => 1,
                'lower_limit' => 0,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -0.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 39,
                'criteria_id' => 16,
                'title' => "Priority",
                'project_type' => 1,
                'lower_limit' => 1,
                'upper_limit' => 2,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 40,
                'criteria_id' => 16,
                'title' => "High priority",
                'project_type' => 1,
                'lower_limit' => 2,
                'upper_limit' => 3,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 41,
                'criteria_id' => 16,
                'title' => "Most priority",
                'project_type' => 1,
                'lower_limit' => 3,
                'upper_limit' => 4,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 42,
                'criteria_id' => 16,
                'title' => "Top most priority",
                'project_type' => 1,
                'lower_limit' => 4,
                'upper_limit' => 5,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 43,
                'criteria_id' => 17,
                'title' => "If they cross (100-180) billable hours per week",
                'project_type' => 2,
                'lower_limit' => 100,
                'upper_limit' => 180,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 20,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 44,
                'criteria_id' => 17,
                'title' => "If they cross 180  billable hours per week",
                'project_type' => 2,
                'lower_limit' => 180,
                'upper_limit' => 180,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '<',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 30,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 45,
                'criteria_id' => 18,
                'title' => "For the billed amounts in hourly projects (Every week) will get 3% of the billed amount",
                'project_type' => 2,
                'lower_limit' => 1,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 1,
                'lower_limit_condition' => '==',
                'upper_limit_condition' => '==',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 46,
                'criteria_id' => 15,
                'title' => "Missing every goal in a regular project",
                'project_type' => 2,
                'lower_limit' => 0,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 47,
                'criteria_id' => 15,
                'title' => "Missing every goal in a priority project",
                'project_type' => 2,
                'lower_limit' => 1,
                'upper_limit' => 2,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 48,
                'criteria_id' => 15,
                'title' => "Missing every goal in a high-priority project",
                'project_type' => 2,
                'lower_limit' => 2,
                'upper_limit' => 3,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -3,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 49,
                'criteria_id' => 15,
                'title' => "Missing every goal in a top most priority project",
                'project_type' => 2,
                'lower_limit' => 3,
                'upper_limit' => 4,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -4,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 50,
                'criteria_id' => 15,
                'title' => "Missing every goal in a critically sensitive project",
                'project_type' => 2,
                'lower_limit' => 4,
                'upper_limit' => 5,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 51,
                'criteria_id' => 19,
                'title' => "If the first submission is made within 100 hours of the award time",
                'project_type' => 2,
                'lower_limit' => 0,
                'upper_limit' => 100,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 1,
                'limit_unit' => 1,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => 5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 52,
                'criteria_id' => 16,
                'title' => "Revision due to PM's fault on regular project",
                'project_type' => 2,
                'lower_limit' => 0,
                'upper_limit' => 1,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -0.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 53,
                'criteria_id' => 16,
                'title' => "Revision due to PM's fault on priority project",
                'project_type' => 2,
                'lower_limit' => 1,
                'upper_limit' => 2,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 54,
                'criteria_id' => 16,
                'title' => "Revision due to PM's fault on high-priority project",
                'project_type' => 2,
                'lower_limit' => 2,
                'upper_limit' => 3,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -1.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 55,
                'criteria_id' => 16,
                'title' => "Revision due to PM's fault on top most priority project",
                'project_type' => 2,
                'lower_limit' => 3,
                'upper_limit' => 4,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
            [
                'id' => 56,
                'criteria_id' => 16,
                'title' => "Revision due to PM's fault on critically sensitive project",
                'project_type' => 2,
                'lower_limit' => 4,
                'upper_limit' => 5,
                'lower_limit_top_range' => null,
                'upper_limit_bottom_range' => null,
                'limit_type' => 2,
                'limit_unit' => 5,
                'lower_limit_condition' => '<',
                'upper_limit_condition' => '>=',
                'lower_limit_top_range_condition' => null,
                'upper_limit_bottom_range_condition' => null,
                'limit_depend_on_models_and_fields' => null,
                'point_type' => 1,
                'points' => -2.5,
                'point_depend_on_model' => null,
                'point_depend_on_field' => null
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('factors');
    }
};
