export const fakeData = [
    {
        id: 1,
        employee_name: "employee",
        task: [
            {
                id: 1,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 2,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 3,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 4,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 5,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 7,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
        ],
    },
    {
        id: 2,
        employee_name: "employee 2",
        task: [
            {
                id: 1,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },

            {
                id: 2,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 3,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 4,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 5,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 6,
                project_name: "Project Name 7",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 7,
                project_name: "Project Name",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
            {
                id: 8,
                project_name: "Project Name 8",
                client: "client",
                project_manager: "Project Manager",
                number_of_session: "Number of session",
                total_tracked_time: "10 hours 25min",
            },
        ],
    },
];
