// dummy data for project status
export const GoalExtentionHistoryTableData = [
  {
    id: 1,
    goal_start_date: "2022-01-01",
    goal_end_date: "2022-01-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 3,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 2,
    goal_start_date: "2022-02-01",
    goal_end_date: "2022-02-28",
    duration: 28,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 5,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 2,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 3,
    goal_start_date: "2022-03-01",
    goal_end_date: "2022-03-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 3,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 4,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Pending",
  },
  {
    id: 4,
    goal_start_date: "2022-04-01",
    goal_end_date: "2022-04-30",
    duration: 30,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 3,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Pending",
  },
  {
    id: 5,
    goal_start_date: "2022-05-01",
    goal_end_date: "2022-05-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 5,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 2,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 6,
    goal_start_date: "2022-06-01",
    goal_end_date: "2022-06-30",
    duration: 30,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 3,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 4,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 7,
    goal_start_date: "2022-07-01",
    goal_end_date: "2022-07-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 5,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },

];


export const projectManagerExplanationData = [
  {
    id: 1,
    goal_start_date: "2024-03-01",
    goal_end_date: "2024-03-15",
    duration: 15,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client: {
      pmId: 123,
      pmName: "John Doe"
    },
    project_name: "Project A",
    reason_status: 0,
    clientName: "John Doe",
    project_budget: 1000,
    currency_symbol: "$",
    project_category: "Regular",
    
  },
  {
    id: 2,
    goal_start_date: "2024-03-10",
    goal_end_date: "2024-03-25",
    duration: 15,
    description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    client: {
      pmId: 456,
      pmName: "Jane Smith"
    },
    project_name: "Project B",
    reason_status: 0,
    clientName: "Jane Smith",
    project_budget: 2000,
    currency_symbol: "$",
    project_category: "Regular",
  },
  {
    id: 3,
    goal_start_date: "2024-03-05",
    goal_end_date: "2024-03-20",
    duration: 15,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    client: {
      pmId: 789,
      pmName: "Alice Johnson"
    },
    project_name: "Project C",
    reason_status: 0,
    clientName: "Alice Johnson",
    project_budget: 3000,
    currency_symbol: "$",
    project_category: "Regular",
  },
  {
    id: 4,
    goal_start_date: "2024-03-15",
    goal_end_date: "2024-03-30",
    duration: 15,
    description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    client: {
      pmId: 101,
      pmName: "Bob Williams"
    },
    project_name: "Project D",
    reason_status: 0,
    clientName: "Bob Williams",
    project_budget: 4000,
    currency_symbol: "$",
    project_category: "Regular",
  },
  {
    id: 5,
    goal_start_date: "2024-03-20",
    goal_end_date: "2024-04-05",
    duration: 16,
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    client: {
      pmId: 112,
      pmName: "Eva Brown"
    },
    project_name: "Project E",
    reason_status: 0,
    clientName: "Eva Brown",
    project_budget: 5000,
    currency_symbol: "$",
    project_category: "Regular",
  },
  {
    id: 6,
    goal_start_date: "2024-03-25",
    goal_end_date: "2024-04-10",
    duration: 16,
    description: "Nulla porttitor accumsan tincidunt. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
    client: {
      pmId: 113,
      pmName: "Michael Wilson"
    },
    project_name: "Project F",
    reason_status: 0,
    clientName: "Michael Wilson",
    project_budget: 6000,
    currency_symbol: "$",
    project_category: "Regular",
  },
  {
    id: 7,
    goal_start_date: "2024-03-30",
    goal_end_date: "2024-04-15",
    duration: 16,
    description: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client: {
      pmId: 114,
      pmName: "Sarah Davis"
    },
    project_name: "Project G",
    reason_status: 0,
    clientName: "Sarah Davis",
    project_budget: 7000,
    currency_symbol: "$",
    project_category: "Regular",
  }
];

